### ISSUE TITLE
Please add condition for invisible item frames

### ISSUE THREAD

**Issue by takatalvi** [JakeGBLP/Lusk#17]
I would like to make invisible item frames available for my players, but with the condition that they will be single-use only, for obvious reasons. Whenever the item is removed from an invisible item frame, the item frame would be killed.

I put together this script:
```
on itemframe remove:
    if world of player is "kreativ":
        if event-entity is invisible:
            kill event-entity
```

I've also tried the condition `if nbt compound of event-entity has nbt tag "Invisible:1b":` (from SkBee) but no success.

Without the condition my script works, but I only want to target invisible item frames, so I deduced that the condition doesn't recognize invisible item frames as invisible entities. Would it be possible to include item frames and glow item frames with the tag Invisible:1b into the invisible entities?

Thanks!

**Comment by JakeGBLP** [comment]
I apologise for the long wait, the is invisible condition is from skript and it doesn't check for anything other than living entities, since you have skbee you can do `if visibility of event-entity is false:` which does what you wanted.

I will add full coverage of the itemframe api and it will be available in Lusk 1.3.

**Comment by takatalvi** [comment]
thank you for the review, i didn't realize it was a base skript functionality. i managed to find a workaround in the meantime by checking nbt compound, but i'll try visibility from skbee too. thanks!

**Comment by JakeGBLP** [comment]
This has been added, a bit ago, actually, but I forgot to note that here.

I've also added the skript issue label since the invisible condition shouldn't fail here.

The new Item Frame elements can be found here:
https://github.com/JakeGBLP/Lusk/blob/main/src/main/java/it/jakegblp/lusk/elements/minecraft/entities/itemframe/conditions/CondItemFrameVisible.java
https://github.com/JakeGBLP/Lusk/blob/main/src/main/java/it/jakegblp/lusk/elements/minecraft/entities/itemframe/expressions/ExprItemFrameIsVisible.java
